### ISSUE TITLE
想问一下里面的插图都是哪里找的…

### ISSUE THREAD

**Issue by miaochiahao** [3gstudent/pdf#1]
PPT里面插图都很有意思，想知道是哪里找到的，请师傅方便的时候告知一下
hhhhh非常抱歉没有找到其他的联系方式，想了想只有放在这了

**Comment by 3gstudent** [comment]
@miaochiahao 去搜矢量图，应该就能找到想要的图片

**Comment by qci133** [comment]
ppt好精美。简洁又直观。
